project_id = "penbfwrbikpkvchbohte"

[functions.google-drive-auth]
verify_jwt = true

[functions.google-drive-callback]
verify_jwt = false

[functions.google-drive-api]
verify_jwt = true

[functions.merge-transcripts]
verify_jwt = true

[functions.google-calendar-event]
verify_jwt = true

[functions.google-tasks-create]
verify_jwt = true

[functions.extract-action-items]
verify_jwt = true

[functions.save-transcript-to-drive]
verify_jwt = true

[functions.upload-photo-to-drive]
verify_jwt = true

[functions.upload-transcriber-file]
verify_jwt = true

